---
# tasks file for db
- name: check if installed postgres
  stat:
    path: /var/lib/pgsql/data
  register: installed

- name: install postgres 
  yum:
    name: postgresql-server
    state: latest
  when: installed.stat.exists == false

- name: enable postgres at boot
  service:
    name: postgresql
    enabled: yes

- name: Check if DB has been initialised
  stat:
    path: /var/lib/pgsql/data
  register: dbinstalled
#  - debug: var=dbinstalled.stat.exists
- name: initilize postgres
  command: postgresql-setup initdb
  when: dbinstalled.stat.exists == false

- name: start postgres
  service:
    name: postgresql.service
    state: started

